### ISSUE TITLE
Port examples from Scala Mu

### ISSUE THREAD

**Issue by serras** [higherkindness/mu-haskell#10]
The Mu repo has [quite some examples](https://github.com/higherkindness/mu/tree/master/modules/examples). We should port them to `mu-haskell`.

- [x] health-check
- [x] route-guide
- [x] todolist
- [x] seed

**Comment by serras** [comment]
The "health check" example has now been ported.

**Comment by serras** [comment]
The "route guide" example has also been ported

**Comment by kutyel** [comment]
The "todolist" has been ported! But we need to think what to do when some service fails! 🤔

**Comment by kutyel** [comment]
Reopen cause "seed" example is still missing!

**Comment by kutyel** [comment]
Seed example has been also migrated! 👏

**Comment by serras** [comment]
Please close the issue and update https://github.com/47deg/marlow/issues/444 when the PR is finally merged.
