### ISSUE TITLE
GraphQL: example applications

### ISSUE THREAD

**Issue by serras** [higherkindness/mu-haskell#123]
Take some examples from Apollo, Sangria, Caliban, or any other GraphQL functional framework, and turn it into a Mu+GraphQL application.

This issue is about the server part, the client part is covered by #86.

**Comment by domenkozar** [comment]
Something that might be good to compare with: https://github.com/morpheusgraphql/morpheus-graphql

**Comment by serras** [comment]
Indeed, our idea is to write a comparison in the docs between Mu-Haskell, Morpheus, and `graphql-api`. Although at the end of the day, the most significant difference is that Mu-Haskell tries to define services for many protocols, whereas the others focus on GraphQL. So the usual trade-off between "not being 100% GraphQL-ish" and "you can reuse more code".

**Comment by nalchevanidze** [comment]
hi, actually both application needs Query Validation and execution( where I have already addressed most of them). so, i could share internal logic and you can use it with your own schema.

so we could join our effort.

**Comment by serras** [comment]
@nalchevanidze unfortunately, I don't think a lot of code sharing is possible in those steps. The way Mu-Haskell executes a query is by using a GADT which follows the shape of the type-level schema. This type-level schema is described using the combinators for the library, which is nice from the type-safety point of view, but unfortunately couples both in a very strong way.

**Comment by serras** [comment]
@domenkozar @nalchevanidze I've written a bit about how Mu compares with `graphql-api` and Morpheus at https://github.com/higherkindness/mu-haskell/pull/174. It would be great if you could have a look, and tell me what you think (and also point any misunderstandings I have of other libreries).

**Comment by nalchevanidze** [comment]
> @nalchevanidze unfortunately, I don't think a lot of code sharing is possible in those steps. The way Mu-Haskell executes a query is by using a GADT which follows the shape of the type-level schema. This type-level schema is described using the combinators for the library, which is nice from the type-safety point of view, but unfortunately couples both in a very strong way.

sorry i did not understand what you meant. 

schema deriving, parsing, validation and execution is divided separate processes in morpheus.
my point is to share validation. if you generate  the schema with your library the and pass into morpheus. 

https://github.com/morpheusgraphql/morpheus-graphql/blob/2a5c17531f0ccc52bf3f0308ce927fd81740d6bf/src/Data/Morpheus/Execution/Server/Resolve.hs#L167

you can get validated request. and after that you can execute it with your resolvers(logic). 

there are lots of validations that should be made. why not join the effort on it.

```gql
query UserFriends {
    user {
     ...Friends
    }
}

fragment Friends on User {
     friends {
        ...Friends    
    }
}
```
causes infinite loop.

or selectionMerging
```gql
query UserFriends {
    user { 
        name
    } 
   { 
     email
   }
}
```
after validation should me merged to:

```gql
query {
    user { 
        name
        email
    } 
}
```

unusedFragment, unusedVariable, VariableMismatch , ....etc.

**Comment by nalchevanidze** [comment]
> @domenkozar @nalchevanidze I've written a bit about how Mu compares with `graphql-api` and Morpheus at #174. It would be great if you could have a look, and tell me what you think (and also point any misunderstandings I have of other libreries).

i leave some comments on PR.  overall its okey.

**Comment by kutyel** [comment]
Isn't this fixed by #174 @serras? 🤔

**Comment by serras** [comment]
This should just be closed once we have an application which showcases all parts of our GraphQL support, including arguments, enums, and subscriptions. Maybe we should enlarge the `library-server` to include this?

**Comment by kutyel** [comment]
Definitely, 👍 today I was also thinking that we lack an example of `mutation`! ☝️

**Comment by serras** [comment]
I have just added a new example in #211, so for now we are well served. Closing this issue.
