### ISSUE TITLE
Better notation for building servers

### ISSUE THREAD

**Issue by serras** [higherkindness/mu-haskell#136]
Right now, building a server requires matching the exact order in which methods and services are defined in the correspoding type. When this type comes from importing a `.proto`, `.avdl`, or in the future GraphQL schema, keeping this order is quite difficult. Furthermore, @kutyel has noticed that the error message you get is quite un-informative.

So we need to find a better notation. Right now we are thinking of a `blaze-builder`-like notation using `do`, like:

```haskell
service @"Book" $ do
  method @"id" ...
  method @"author" ...
```

@arianvp you might be interested in this

**Comment by arianvp** [comment]
How will you make sure that you get a type error when you 'miss' a certain field of rpc call?

Could perhaps fixed by using OverloadedSyntax and use `IxMonad`, but then you enforce implicit ordering again...

**Comment by serras** [comment]
Sure, the goal is to get a compile-time error if you miss something. I was also thinking along the lines of `RebindableSyntax`, but I'm not so happy with the idea, because that makes inference in the rest of the file terrible :(

**Comment by serras** [comment]
Here's my first attempt: https://github.com/higherkindness/mu-haskell/blob/better-server-api/core/rpc/src/Mu/Rpc/Examples.hs#L75

@kutyel @arianvp what do you think?

Unfortunately, I could not get a good error message for the case in which you are missing a method. The reason is that for the inference to work I need to have a functional dependency on `ToHandlers`. But that dependency precludes me from having [this instance](https://github.com/higherkindness/mu-haskell/blob/better-server-api/core/rpc/src/Mu/Server.hs#L249).

**Comment by serras** [comment]
@arianvp after some discussion with @kutyel, we came with a better API using tuples instead of weird heterogeneous lists. So you can now declare servers in this way:

```haskell
singleService ( method @"SayHello" sayHello
              , method @"SayManyHellos" sayManyHellos
              , method @"SayHi" sayHi )
```

and GraphQL resolvers as follows:

```haskell
resolver
  ( object @"Author" ( field @"name"   authorName
                     , field @"books"  authorBooks )
  , object @"Book"   ( field @"author" (pure . snd)
                     , field @"title"  (pure . fst) ) )
````

What do you think? I find it quite nice :)
