### ISSUE TITLE
Support 'avro' 0.5

### ISSUE THREAD

**Issue by serras** [higherkindness/mu-haskell#162]
There is [a new release of the `avro` package](http://hackage.haskell.org/package/avro-0.5.0.0) which is not backwards-compatible with the previous one. We need to update our code to use it.

This issue depends on https://github.com/higherkindness/avro-parser-haskell/issues/7.

**Comment by kutyel** [comment]
The issue in the parser has been fixed by https://github.com/higherkindness/avro-parser-haskell/pull/8 🚀

**Comment by serras** [comment]
There are some issues with the `avro` library which may need to be fixed before we go all in:
- https://github.com/haskell-works/avro/issues/142 (*`toAvro` does not work well in the presence of `NamedType`*) -> I was able to work around this
- https://github.com/haskell-works/avro/issues/143 (*Deconflicting record with different orderings*) -> this is important for compatibility with other libraries, for example the Python library sets the ordering, but we don't

**Comment by serras** [comment]
Closed by #164
