### ISSUE TITLE
Protobuf: decoding a packed repeated enum field

### ISSUE THREAD

**Issue by cb372** [higherkindness/mu-haskell#163]
Something I picked up in the mu-scala integration tests I'm writing.

```proto
syntax = "proto3";

package integrationtest;

message GetForecastRequest {
  string city = 1;
  reserved 2 to 4;
  int32 days_required = 5;
}

message GetForecastResponse {
  enum Weather {
    SUNNY = 0;
    CLOUDY = 1;
    RAINY = 2;
  }

  string last_updated = 1;
  repeated Weather daily_forecasts = 2;
}

service WeatherService {
  rpc getForecast(GetForecastRequest) returns (GetForecastResponse);
}
```

The mu-scala server encodes the `daily_forecasts` repeated enum field using [packed encoding](https://developers.google.com/protocol-buffers/docs/encoding#packed). It appears the mu-haskell client cannot decode it. The field gets set to `Nothing`.

If I tweak things on the Scala side to stop using packed encoding, the mu-haskell client can decode the field just fine.

I've [confirmed](https://github.com/47degrees/pbdirect/pull/66) that the official protoc CLI tool also encodes repeated enum values using packed encoding. So it seems like mu-scala is doing the right thing and mu-haskell should be able to decode it.

I guess the fix for this would be in [protoc-wire](https://github.com/awakesecurity/proto3-wire/blob/master/src/Proto3/Wire/Decode.hs)?

**Comment by serras** [comment]
There's in fact [a way](https://github.com/awakesecurity/proto3-wire/blob/master/src/Proto3/Wire/Decode.hs#L413) to deal with packed encodings in the `proto3-wire` library. This might require a bit of engineering, since we should only try this for those types for which packed encoding makes sense, but definitely doable.
