### ISSUE TITLE
Mysterious zero byte at start of Avro-encoded message

### ISSUE THREAD

**Issue by cb372** [higherkindness/mu-haskell#192]
I'm upgrading the Mu-Scala integration tests to Mu-Haskell v0.3, and seeing some strange changes in behaviour since v0.2. Stand by for a few more issues this week 😄 

## Scenario

Mu-Scala server, Mu-Haskell client, Avro encoding.

## Request schema (in `.avdl` format)

```
  record GetForecastRequest {
    string city;
    int days_required;
  }
```

## Request message

```
GetForecastRequest(city = "London", days_required = 3)
```

## Expected Avro-encoded bytes

```
0c 4c 6f 6e 64 6f 6e 06
```

Explanation:

* `0c .. 6e` is the value of `city`, i.e. the string `London`
    * `0c` is the length, 6, in zig-zag encoding
* `06` is the value of `days_required`, i.e. `3` in zig-zag encoding

This is what Mu-Haskell v0.2 sends. It also matches what is generated by a Scala Avro library I tried.

## Actual bytes

```
00 0c 4c 6f 6e 64 6f 6e 06
```

Note the strange `00` byte at the start.

(Aside: the Mu-Haskell client compresses the message using GZip. So those 9 bytes get compressed (really poorly!) and end up as 29 bytes on the wire.)

## Result

Mu-Scala's Avro decoding implementation tries to decode these bytes as a list of messages, then use the head of the list as its result. So it decodes `00 0c` as `GetForecastRequest(city = "", days_required = 6)`, then blows up trying the decode the remaining bytes as another message.

## Packet captures

I've prepared Wireshark captures of Mu-Haskell v0.2 vs v0.3 but I can't attach them here. Let me know if you want them.

**Comment by cb372** [comment]
I have a better idea now where that `00` byte is coming from.

I tried the test the other way around, with a Mu-Scala client calling a Mu-Haskell server.

The client sent the "expected Avro-encoded bytes" shown above. So the first byte was `0c`, which is the numeric value 6 (zig-zag encoded). The Haskell server responded with this error:

```
done-error: Decoded Avro tag is outside the expected range for a Union.
Tag: 6
union of: [
  (0,Record {
    name = "GetForecastRequest",
    aliases = [],
    doc = Nothing,
    fields = [
      ReadField {
        fldName = "city",
        fldAliases = [],
        fldDoc = Nothing,
        fldOrder = Nothing,
        fldStatus = AsIs 0,
        fldType = String {logicalTypeS = Nothing},
        fldDefault = Nothing
      },
      ReadField {
        fldName = "days_required",
        fldAliases = [],
        fldDoc = Nothing,
        fldOrder = Nothing,
        fldStatus = AsIs 1,
        fldType = Int {logicalTypeI = Nothing},
        fldDefault = Nothing
      }
    ]
  }),
  (1,Record {
    name = "GetForecastResponse",
    aliases = [],
    doc = Nothing,
    fields = [
      ReadField {
        fldName = "last_updated",
        fldAliases = [],
        fldDoc = Nothing,
        fldOrder = Nothing,
        fldStatus = AsIs 0,
        fldType = String {logicalTypeS = Nothing},
        fldDefault = Nothing
      },
      ReadField {
        fldName = "daily_forecasts",
        fldAliases = [],
        fldDoc = Nothing,
        fldOrder = Nothing,
        fldStatus = AsIs 1,
        fldType = Array {item = NamedType "Weather"},
        fldDefault = Nothing
      }
    ]
  }),
  (2,Enum {
    name = "Weather",
    aliases = [],
    doc = Nothing,
    symbols = ["SUNNY","CLOUDY","RAINY"]
  })
]
```

So it looks like Mu-Haskell server is expecting the first byte of the message to be the tag for a discriminated union. And I assume the Mu-Haskell client would prepend that tag to its request messages as well.

I don't know why those 3 types are gathered together in a union. The protocol was generated from this `.avdl`:

```
@namespace("integrationtest")
protocol WeatherService {

  record GetForecastRequest {
    string city;
    int days_required;
  }

  enum Weather {
    SUNNY,
    CLOUDY,
    RAINY
  }

  record GetForecastResponse {
    string last_updated;
    array<Weather> daily_forecasts;
  }

  void ping();

  GetForecastResponse getForecast(GetForecastRequest req);

}
```

**Comment by serras** [comment]
Yes, I arrived to the same conclusion. I think this came as part of the big refactor due to the new version of the `avro` package.

Anyway, I always had difficulties with that part of the [specification](https://avro.apache.org/docs/current/spec.html#schemas). In particular, the *Schema Declaration* section reads:

> A Schema is represented in JSON by one of:
> - ...
> - A JSON array, representing a union of embedded types.

In fact, in the `HasSchema` implementation for `WithSchema` we wrap everything in a `Union` from the `avro` package in order to put together all the types in the schema.

**Comment by serras** [comment]
In any case, I've done a preliminary fix of the bug in https://github.com/higherkindness/mu-haskell/commit/8b1f2555150450ecc282b92b93b8fc7e1ba79191. Could you check that it works? In theory you can tell Stack to use that version instead of the released one by changing the `extra-deps` related to Mu by:

```
- git: https://github.com/higherkindness/mu-haskell.git
  commit: 8b1f2555150450ecc282b92b93b8fc7e1ba79191
  subdirs:
  - core/schema
  - core/rpc
  - core/optics
  - adapter/avro
  - adapter/protobuf
  - grpc/common
  - grpc/server
  - grpc/client
```
