### ISSUE TITLE
gRPC client does not send a message when calling a zero-arg Avro method

### ISSUE THREAD

**Issue by cb372** [higherkindness/mu-haskell#193]
## Scenario

Avro encoding.

Method definition (in `.avdl` format):

```
  void ping();
```

## Expected result

The HTTP/2 request should contain a DATA frame containing a 0-length gRPC message. So the DATA frame body should be 5 bytes long: 1 byte for compression flag + 4 bytes for the message length.

## Actual result

The request contains a 0-length DATA frame. There is no gRPC message, which is not valid behaviour.

Actually the [gRPC protocol spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) is a bit vague on this point, but the implication is there there will always be at least one message and never an empty DATA frame.

The server (Mu-Scala, which uses the official Java gRPC server implementation) certainly doesn't like it. It responds with status 13 (`INTERNAL`) and message `Half-closed without a request`.

**Comment by serras** [comment]
This is indeed quite weird. The [implemention](https://github.com/haskell-grpc-native/http2-grpc-haskell/blob/master/http2-grpc-proto3-wire/src/Network/GRPC/HTTP2/Proto3Wire.hs#L48) of encoding always adds those two elements to the query.

**Comment by serras** [comment]
Found it, there was some overriding of the default behavior especifically for empty tuple. https://github.com/higherkindness/mu-haskell/commit/821fcf5b396e91e98fa069f7b06be86bd78de1c6 should contain a fix.

**Comment by cb372** [comment]
Fixed in #194
