### ISSUE TITLE
Distributed tracing

### ISSUE THREAD

**Issue by serras** [higherkindness/mu-haskell#196]
Provide distributed tracing in a similar way as [Mu-Scala does](https://www.47deg.com/blog/mu-scala-0-22/#distributed-tracing-with-natchez-1).

**Comment by arianvp** [comment]
Solved by https://github.com/higherkindness/mu-haskell/tree/09820afca15685fd4cf6d4d88b9e509bc572394c/instrumentation/tracing ?

**Comment by serras** [comment]
There's still some work to be done for clients passing this information when called from servers which sopport tracing. That way everything works automatically.

**Comment by kutyel** [comment]
Closing because we have right now at least _some form_ of **distributed tracing**, can be reopened or followed up by enhancement PRs in the future 😉
