### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by serras** [higherkindness/mu-haskell#197]
Support metrics as [Mu-Scala does](https://higherkindness.io/mu-scala/guides/metrics-reporting).

**Comment by serras** [comment]
Relevant -> https://github.com/higherkindness/mu-scala/blob/master/modules/metrics/prometheus/src/main/scala/higherkindness/mu/rpc/prometheus/PrometheusMetrics.scala

**Comment by kutyel** [comment]
@serras should this be closed as of #198? 😉

**Comment by serras** [comment]
Not really, we may want to add additional metrics providers.

**Comment by kutyel** [comment]
Closing because we have right now at least _some form_ of **metrics (via prometheus)**, can be reopened or followed up by enhancement PRs in the future 😉
