### ISSUE TITLE
Question: GraphQL enum

### ISSUE THREAD

**Issue by shineli-da** [higherkindness/mu-haskell#203]
How do I handle the enum argument like below? is there an example for service mapping and resolver of enum type? 
```graphql
...
enum CompaniesOrder {
  score_ASC
  variance_DESC
}

type Query {
  companies(
    order: CompaniesOrder
  ): [Company!]!
}
```

**Comment by serras** [comment]
I have updated the [`seed` example](https://github.com/higherkindness/mu-haskell/tree/2840d91a650948999629ba189bf4f8f412bd53dd/examples/seed/src) to use enumerations
