### ISSUE TITLE
Docs for mapping custom types to/from primitive protocol types

### ISSUE THREAD

**Issue by coderfromhere** [higherkindness/mu-haskell#208]
Hi,  the current docstring sections for `ToSchema` and `FromSchema` don't explain the way I can define a conversion to/from protobuf `bytes` and Haskell `Data.UUID.UUID`. How would I define such a type? How would I reject incorrect byte values that are not valid UUID?

**Comment by serras** [comment]
We figured out that there was no support for having a Haskell type different from the underlying type defined by each protocol. @coderfromhere would #208 fix your problem? Now you can state that your data is a `UUID` but on the wire it moves as a `ByteString` by defining the field as `Underlying ByteString UUID`.

**Comment by coderfromhere** [comment]
Yes, thank you!
