### ISSUE TITLE
Docs for auto-deriving 'Maybe a'

### ISSUE THREAD

**Issue by coderfromhere** [higherkindness/mu-haskell#209]
Hi, for some reason my custom `Maybe a` (where `a` is one of the primitive types - Text, ByteString, Int64) fields break auto-deriving of `ToSchema` and `FromSchema` protobuf bindings, and I couldn't find an example of such a type being used in examples listed in the official documentation.

Do I have to manually define the schema if I want a Maybe of a primitve type, as it's shown in https://github.com/higherkindness/mu-haskell/blob/b0f84869674868aa66c5387dbc1b74ca8840e4c8/core/schema/src/Mu/Schema/Examples.hs#L75 ?

**Comment by serras** [comment]
We actually struggled with this same problem when creating the library. However, according to the [Protocol Buffers docs](https://developers.google.com/protocol-buffers/docs/overview#optional):

> If the default value is not specified for an optional element, a type-specific default value is used instead: for strings, the default value is the empty string. For bytes, the default value is the empty byte string. For bools, the default value is false. For numeric types, the default value is zero. For enums, the default value is the first value listed in the enum's type definition.

That means that in a Protocol Buffers message it is not possible to have `Maybe p` where `p` is primitive, since a lack of such a field means that the default value is to be used. In fact, some guides expect Protocol Buffers implementations to drop such values in order to save bandwidth.

I'm closing this since it cannot be fixed without getting out of the spec. Feel free to ask any further questions :)

**Comment by coderfromhere** [comment]
Hi @serras , I appreciate your comment, it clarifies the limitations of protobuf to me.

**Comment by serras** [comment]
Great idea! I'm going to re-open this so I don't forget to do it

**Comment by coderfromhere** [comment]
Thank you!

**Comment by serras** [comment]
@elenavielva gave me an idea today: if you *really* need an optional of primitive type, you can wrap it on an object with a single field of that type. In that case Protocol Buffers is able to know the difference between a missing object, and an object where the field has the default value.

**Comment by coderfromhere** [comment]
Yeah, I thought about a similar idea yesterday - if every required field is encoded as `repeated` then an empty container would indicate a value omission and a single element with a zero value would indicate a client intent to pass an actual value that happens to be the same as the zero value of that type. While it will do, still I don't like the fact that those checks to disambiguate an intend from an error will not happen at compile time for a client and the verification logic is shared between the `proto` spec and Haskell parsers of specific types.

**Comment by coderfromhere** [comment]
Maybe `NonEmpty a` would help in that case in Haskell, but my clients are in Python and I'd like to leverage as much MyPy linting power as possible for them and this approach will require a custom implementation of the protobuf->python codegen.
