### ISSUE TITLE
Support generating RPC web servers from Mu Schemas

### ISSUE THREAD

**Issue by andremarianiello** [higherkindness/mu-haskell#215]
I want define my services and message types using .proto files (like with grpc) but use those endpoints from a browser (some combination of simple requests for unary RPCs and fetch/websockets for streaming RPCs). Does mu-haskell support this? I know there are products like grpc-web that allow you to communicate between a browser and a grpc server, but require a proxy to translate, but I would like to avoid using a proxy if possible. Now I don't know mu-haskell and its subcomponents very well, but I don't know of any reason why one couldn't convert proto->schema->http server (possibly utilizing the servant types?). Having this capability would greatly simplify the code I need to write for a web service I am working on, and could be immensely useful. If don't know of any product that makes proto services directly accessible from a browser since they all use grpc. If this is something that should be possible but simply hasn't been done I would be interested in diving deeper into mu-haskell to figure how to implement it. Thanks in advance.

**Comment by serras** [comment]
As a simple, yet powerful, work around, you can expose the gRPC services using the GraphQL protocol, which then can be queried using libraries available in JavaScript like urql or Apollo.

Our [health check example](https://github.com/higherkindness/mu-haskell/blob/master/examples/health-check/src/Server.hs#L51) does exactly that: takes one single `.proto` file and exposes it using gRPC with Protocol Buffers and Avro serialization, and also as GraphQL.

Please don't hesitate to ask any further questions.

**Comment by andremarianiello** [comment]
I could be wrong, but I don't think that the service I'm developing is a good fit for the graphql use case. It is much more powerful than I need (since I really only need some specific RPCs), so implementing the graphql handlers would be more work than implementing the grpc-style handlers. GraphQL is not nearly as ubiquitous as as standard REST-ish apis, so using graphql would limit integration possibilities. Finally, I want the ability to do client and bidirectional streaming, which I don't think graphql supports. Feel free to correct any wrong assumptions I have made about graphql, I haven't used it much.

**Comment by serras** [comment]
If your service uses only simple and streaming methods, turning it into GraphQL is as simple as asking Mu to serve it as GraphQL, no need to write any different handlers.

Bidirectional streaming is more complicated, since I don't know any simple way to do that kind of communication in a browser.

**Comment by andremarianiello** [comment]
Websockets should be able to do it

**Comment by andremarianiello** [comment]
If this isn't on your roadmap and don't want it to be, I will understand. I'm sure it is a lot of work for an unknown amount of benefit.

**Comment by andremarianiello** [comment]
I have a prototype that turns a Mu.Server.ServerT into a Servant.ServerT, using mu-grpc-server as a reference. It also includes a type family that maps Method+handler types to a Servant API. I don't have streaming yet, but it looks very doable. Are you interested in a PR?

**Comment by serras** [comment]
Sure, bring it in! This is something we've been investigating and considering ourselves, but never materialized due to lack of time. However, if you bring an initial implementation, we would be happy to maintain it as part of Mu.

**Comment by andremarianiello** [comment]
That is great news! I'll make a WIP MRas soon as possible.

**Comment by andremarianiello** [comment]
I built the prototype against 0.3.0.0, but that is very different from master, so that might delay my MR a bit.
