### ISSUE TITLE
Replace Travis CI with Github Actions (Stack)

### ISSUE THREAD

**Issue by kutyel** [higherkindness/mu-haskell#22]
Since [some](https://github.com/arrow-kt/arrow/pull/1694/files) projects of 47 are moving to Github Actions, I think it would be a great idea to do the same!

Besides, I think it'd a great chance to **create our own Github action** for [Stack](https://docs.haskellstack.org/en/stable/README/) (since Github's one uses Cabal 3.0) and the rest of the Haskell community would benefit from it! 🎉 (maybe @gimenete can provide some guidance on how to do this 😉)

**Comment by kutyel** [comment]
Advancements have been made in this regard (see this: https://github.com/kutyel/haskell-book/commit/4c0e4b24ec125b08106333ceecb59e2a9ac35e02). However, we have stumbled with the fact that Stack caches are **huge** and Github Actions cache currently has a [limit](https://github.com/actions/cache#cache-limits) of 400Mb per individual cache, we need to investigate if there's a way to work through this or else we'll be stuck with travis.

**Comment by kutyel** [comment]
Since Github Actions with Stack and no cache is not an option (right?), the best solution right know is to use cachix/nix, if you agree @serras I can do the PR, it's quite easy 😝

**Comment by serras** [comment]
I am happy to have a good CI pipeline in our project. It would be even better if we could have more fine-grained reports, like failures for different `stack.yaml` versions.

**Comment by rachelcarmena** [comment]
Maybe this GitHub Action is useful for you: https://github.com/actions/setup-haskell

**Comment by rachelcarmena** [comment]
For having different reports, I used this action: https://github.com/actions/upload-artifact and then they can be reviewed or downloaded from UI.

**Comment by rachelcarmena** [comment]
We also created a bot for creating issues in case of failure with new Kotlin EAP versions and pull requests in case of success. Let me know if I can help you!

**Comment by rachelcarmena** [comment]
And here another action for Haskell from Github Actions Marketplace: https://github.com/marketplace/actions/haskell-linter

**Comment by serras** [comment]
The [first attempt](https://github.com/higherkindness/mu-haskell/issues/22#issuecomment-558159118) by @kutyel stumbled upon a small cache for the amount of space Haskell project typically need to execute (long story short, in Haskell-land there's no notion of "binary libraries", so everything must be downloaded and compiled locally).
@rachelcarmena do you have any ideas on how to surmount that problem? Or do you think that we should take a different approach (@kutyel suggests using `cachix`, a service to cache Haskell builds)?

**Comment by rachelcarmena** [comment]
> @rachelcarmena do you have any ideas on how to surmount that problem? Or do you think that we should take a different approach (@kutyel suggests using `cachix`, a service to cache Haskell builds)?

Thanks for the info @serras ! Oh, sorry, I didn't have that problem so far. I found this option which solves the problem with additional infrastructure (it supports syncing to an archive directory or to an S3 bucket): https://github.com/haskell-works/cabal-cache

Maybe it's useful to start a topic about that problem here: https://github.community/t5/GitHub-Actions/bd-p/actions

Oh! I think I'm becoming a fan of GitHub Actions... :flushed:

**Comment by afcowie** [comment]
Would @mstksg's https://github.com/marketplace/actions/setup-stack be any help to you?

**Comment by kutyel** [comment]
Hi @afcowie! Thanks for the recommendation, we tried that but could not easily cache stack with github actions, that’s why we chose to try cachix, we’re quite happy so far! 😊
