### ISSUE TITLE
Refactor TH to use "Stagged Sums of Products" 🧨

### ISSUE THREAD

**Issue by kutyel** [higherkindness/mu-haskell#226]
https://www.kosmikus.org/StagedSOP/staged-sop-paper.pdf

**Comment by serras** [comment]
Unfortunately, Typed Template Haskell is not yet there. From the paper (page 4, beginning of section 3):

> Despite the similarity in name, Typed Template Haskellis rather different to Template Haskell and concerns itselfonly with expressions. We cannot manipulate arbitrary syntax trees, and cannot write code that generates datatypes, classes, or **other top-level declarations**.

We use TH specifically to generate **types**, so it's out of our hands now.
