### ISSUE TITLE
Nix shell should generate and run correctly Python tests 🐍

### ISSUE THREAD

**Issue by serras** [higherkindness/mu-haskell#232]
If I execute `nix-shell python-test.nix`, I am welcomed with the following message:

```
error: expression does not evaluate to a derivation (or a set or list of those)
```

This is not great, because we cannot check for inconsistencies with the official implementations of Avro and Protocol Buffers.

It would be great too if this could be integrated as part of CI (it was at some point, but it has disappeared).

**Comment by kutyel** [comment]
The work is basically to fix this nix shell https://github.com/higherkindness/mu-haskell/blob/master/python-test.nix and run it on CI 😄

**Comment by serras** [comment]
As of now it's better to run the Python script manually. Closing then for now.
