### ISSUE TITLE
Support unsigned integers in protobuf?

### ISSUE THREAD

**Issue by akshaymankar** [higherkindness/mu-haskell#245]
I see that unsigned integers are not supported in protobuf and it [looks intentional](https://github.com/higherkindness/mu-haskell/blob/678cd71f5c0628c05d77298fb9e91155801dfd1a/adapter/protobuf/src/Mu/Quasi/ProtoBuf.hs#L115).
I think (perhaps naively) that they can simply be represented by `Word32` and `Word64` from `Data.Word`. Is there a reason why this doesn't work?

**Comment by serras** [comment]
Nothing in particular, I guess we just went with the simpler route and then forgot to add the missing types. Thanks for taking care of this and sending a PR. This will be available in the next release, just shout if you need it earlier.
