### ISSUE TITLE
Library example breaks in 25 seconds of inactivity

### ISSUE THREAD

**Issue by VladimirLogachev** [higherkindness/mu-haskell#262]
Hi!

An interesting thing was introduced by 73a17786c58f70fb024416588db2d832ad6f733e (Fix GraphQL example + pools in mu-persistent).

### Steps to reproduce:

1. Run `stack run library`
2. Wait at least 25 seconds
3. Run a simple query
```sh
curl -X POST \
    -H "Content-Type: application/json" \
    -d '{
        "query": "{
          books {
            title
          }
        }" 
      }' \
    http://localhost:8000
```
Output: 
```
Something went wrong
```
Logs: 
```
starting GraphQL server on port 8000
[Debug#SQL] SELECT "id", "title", "image_url", "author" FROM "book" WHERE ("title"LIKE?) ORDER BY "title"; [PersistText "%"]
SQLite3 returned ErrorError while attempting to perform prepare "SELECT \"id\", \"title\", \"image_url\", \"author\" FROM \"book\" WHERE (\"title\"LIKE?) ORDER BY \"title\"": no such table: book
```

But if any query is executed every 20 seconds, then everything seems to be fine 😀

**Comment by kutyel** [comment]
I guess this is a consequence of opening a `pool` of db connections in persistent, maybe the limit can be increased @serras ?

**Comment by VladimirLogachev** [comment]
As far as I understood, it does not depend on limit. Looks like it's an internal story

**Comment by serras** [comment]
This might be also related to the fact that now there is a ping every 30 seconds, maybe this should be decreased to ensure that the connection is still valid?

**Comment by VladimirLogachev** [comment]
(My observations work with queries, HTTP)
