### ISSUE TITLE
Support for maps in protobuf

### ISSUE THREAD

**Issue by akshaymankar** [higherkindness/mu-haskell#267]
I see that they're [explicitly not supported](https://github.com/higherkindness/mu-haskell/blob/e99149be9f7a70e8c67c2b3ccd3ac1cd50e3606b/adapter/protobuf/src/Mu/Adapter/ProtoBuf.hs#L356-L359) and print a type error. What would it take to support them? Do y'all have a preference between different map types which exist?

**Comment by kutyel** [comment]
I think the Map from `containers` is good enough, right @serras? 😆
