### ISSUE TITLE
Source code for Hello World example

### ISSUE THREAD

**Issue by llattila** [higherkindness/mu-haskell#275]
I have been trying to implement the Hello World in the https://higherkindness.io/mu-haskell/intro-rpc/ and I only seem to get type errors on the server level. Would it be possible to have the source code for the examples available as the introduction is extremely difficult to follow due to Template Haskell, Optics stuff, and a lot of unusual language extensions. Also, it seems there has been different versions going on because there are both HelloResponse and HelloReply in different parts of the web-page.

**Comment by kutyel** [comment]
Hi! @serras will work soon on the examples to update them and try to make them more user-friendly, since the API has been simplified from the last time, sorry about that! And thanks for bringing it up! 😉

**Comment by llattila** [comment]
The `routeguide` seems to be a relatively simple example showing all the four default `protobuf` use-cases. Perhaps add something to `readme` in the meanwhile to work as a starting point for new users?

**Comment by stevenarvar** [comment]
I am not using the optic or lens version of the example, but here is a sample code which does not have build errors:

First use the template given:
```
stack new quickstart https://raw.githubusercontent.com/higherkindness/mu-haskell/master/templates/grpc-server-protobuf.hsfiles -p "author-email:your@email.com" -p "author-name:Your name"
```

Here is my quickstart.proto file:
```
syntax = "proto3";

import "google/protobuf/empty.proto";

package quickstart;

service Service {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest { string name = 1; }
message HelloReply { string message = 1; }
```

Here is my Schema.hs file:
```
{-# language DataKinds             #-}
{-# language DeriveAnyClass        #-}
{-# language DeriveGeneric         #-}
{-# language DuplicateRecordFields #-}
{-# language FlexibleContexts      #-}
{-# language FlexibleInstances     #-}
{-# language MultiParamTypeClasses #-}
{-# language PolyKinds             #-}
{-# language TemplateHaskell       #-}
{-# language TypeFamilies          #-}
{-# language TypeOperators         #-}

module Schema where

import Data.Text as T
import GHC.Generics

import Mu.Quasi.GRpc
import Mu.Schema

grpc "TheSchema" id "quickstart.proto"

-- Map to Haskell types
data HelloRequestMessage
  = HelloRequestMessage { name :: T.Text }
  deriving (Eq, Show, Generic
           , ToSchema   TheSchema "HelloRequest"
           , FromSchema TheSchema "HelloRequest")

data HelloReplyMessage
  = HelloReplyMessage { message :: T.Text }
  deriving (Eq, Show, Generic
           , ToSchema   TheSchema "HelloReply"
           , FromSchema TheSchema "HelloReply")

```

Here is my Main.hs file:
```
{-# language DataKinds             #-}
{-# language TypeApplications      #-}
{-# language FlexibleContexts      #-}
{-# language PartialTypeSignatures #-}
{-# language OverloadedStrings     #-}
{-# language OverloadedLabels #-}
{-# OPTIONS_GHC -fno-warn-partial-type-signatures #-}

module Main where

import Mu.GRpc.Server
import Mu.Server

import Schema

main :: IO ()
main = runGRpcApp msgProtoBuf 8080 server

server :: MonadServer m => SingleServerT i Service m _
server = singleService (method @"SayHello" sayHello)    

sayHello :: (MonadServer m) => HelloRequestMessage -> m HelloReplyMessage
sayHello (HelloRequestMessage nm)
  = pure $ HelloReplyMessage ("hi, " <> nm)
```

I expect if we need to get the lens or optic version of the sample working, we will need to install lens or optic correct and import the proper packages.  The [example](https://github.com/higherkindness/mu-haskell/tree/master/examples) project might be helpful.

**Comment by serras** [comment]
I've double checked the templates and the introductory material, and made the required changes in #326.
