### ISSUE TITLE
Will the libraries in this project be added to stackage?

### ISSUE THREAD

**Issue by jschaul** [higherkindness/mu-haskell#278]
At the moment, when using stack in a project and wanting to use `mu-grpc-server` (or any other libraries from this repository), all the libraries need to be added explicitly as extra-deps. I can see they are not yet in the [latest nightly](https://www.stackage.org/nightly-2021-01-13)

Since the maintainers of a library also need to be the stackage maintainers, this isn't really work someone else can do.

See also https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package

What is your plan on this?

**Comment by kutyel** [comment]
Hi, we (@serras and I) would love to have all the mu family of libraries on Stackage (as we already have the [avro parser](https://www.stackage.org/lts-16.29/package/language-avro-0.1.3.1)) but, unfortunately, many of our dependencies are not yet on Stackage either, so we can't do this at the moment.

**Comment by serras** [comment]
Closing this for now. We usually prune the set of dependencies out of Stackage with every new LTS release, but unfortunately in the latest one the `http2` family of packages is still outdated :(
