### ISSUE TITLE
Contributing guide incomplete

### ISSUE THREAD

**Issue by jschaul** [higherkindness/mu-haskell#279]
Hi again! As I was trying out just compiling the project, I noticed two problems: `stack build` failed due to 1) examples/library/backend not being found and 2) rdkafka headers not being available.

This would be my suggestion for an added section to the contributing guide at `DEVELOPMENT.md`:

```markdown

## Setting up the project

### Native dependencies

The included `adapter/kafka` project requires development headers of the rdkafka library.
* on macOS you can install `sudo brew install librdkafka`
* on fedora you can install `sudo dnf install librdkafka-devel`
* on debian you can install `sudo apt-get install librdkafka-dev`
* when using nix you can TODO?

### git submodules

This project uses git submodules (notably for examples/library/). You can run `git submodule update --init --recursive` once after checkout, or `git config --global submodule.recurse true` to globally enable submodules.
```

You seem to be using nix and cachix in some github actions. I'm not entirely familiar here, could you also add a few lines on how a developer can make use of nix-provided dependencies when working with this project?

**Comment by kutyel** [comment]
Hey @jschaul, this is great! Feel free to open a PR modifying the markdown file and we'll help you adding the remaining nix stuff! 🙌🏻
