### ISSUE TITLE
Protobuf: Enums have default values they shouldn't be required to be Maybe

### ISSUE THREAD

**Issue by akshaymankar** [higherkindness/mu-haskell#282]
If I have a protobuf like this:
```proto
enum MyEnum {
  Option1 = 0;
  Option2 = 1;
}

message MyMessage {
  MyEnum thing1 = 1;
  string thing2 = 2;
}
```

I am forced to create a data structure like this:

```haskell
data MyEnum = Option1 | Option2
data MyMessage = MyMessage { thing1 :: Maybe MyEnum, thing2 :: Text }
```

If I try to encode `MyMessage (Just Option1) "something"` and immediately decode it, I will get `MyMessage Nothing "something"`. This is because enums default to the first value and so in protobuf they are encoded the same as being not specified.

I think the `protobuf` and `grpc` TH functions should make the schema in a way that enums are not marked as optional.

**Comment by akshaymankar** [comment]
This comment explains the situation better (only the reasoning also applies to enums): https://github.com/higherkindness/mu-haskell/pull/130#issuecomment-596433307

**Comment by jschaul** [comment]
(I think 'bug' is a better label than 'enhancement': serializing and deserializing a protobuf object should give back the same type and not eat Option1 and replace it with Nothing).

**Comment by serras** [comment]
Thanks for the report and sorry for the slow reply.

The [guide](https://developers.google.com/protocol-buffers/docs/proto3#enum) shows that this is actually more subtle:

> [...] every enum definition must contain a constant that maps to zero as its first element. This is because:
> - There must be a zero value, so that we can use 0 as a numeric default value.
> - ...

There are a couple of solutions here:
1. Include a special "default value" annotation, as we do in the GraphQL version;
2. Include special logic to check is something is an enum, and if so figure out this default value.

Right now I'm leaning towards (2), but maybe some other have a different opinion.
