### ISSUE TITLE
Protoc plugin for auto generation of Haskell source code?

### ISSUE THREAD

**Issue by tim2CF** [higherkindness/mu-haskell#286]
Hello! Thanks for the gRPC library and tutorial. Are there any plans to implement protoc plugin to auto-generate boilerplate Haskell source code of  types/classes/instances/clients/servers directly from given `.proto` files?

**Comment by serras** [comment]
Using the [`mu-optics`](https://higherkindness.io/mu-haskell/optics/) package you can get away without creating any types. Apart from that, one of our design decisions in Mu has been to *not* pursue that path, because we think being explicit is a win in this case.
