### ISSUE TITLE
oneof - more than 2 options

### ISSUE THREAD

**Issue by rwakulszowa** [higherkindness/mu-haskell#296]
Sorry if this has been asked before, but I'm having a hard time trying to map `oneof` fields with more than 2 fields to Hs.

From what I understand, two field oneofs, such as
```
message OneOfTwo {
  oneof value {
    string a = 1;
    bool b = 2;
  }
}
```
can be mapped to 
```
data OneOfTwo 
  = OneOfTwo { value :: Either T.Text Bool }
   deriving (Eq, Show, Generic
             , ToSchema   TheSchema "OneOfTwo"
             , FromSchema TheSchema "OneOfTwo")
```
This compiles just fine.

How do I represent messages with 3 variants?
```
message OneOfThree {
  oneof value {
    string a = 1;
    bool b = 2;
    int32 c = 3;
  }
}   
```

I've tried nesting `Either`s, but with no success:
```
data OneOfThree
    = OneOfThree { value :: Either T.Text (Either Bool Int32) }
    deriving (Eq, Show, Generic
                  , ToSchema   TheSchema "OneOfThree",
                  , FromSchema TheSchema "OneOfThree")    
```
gives the following error:
```
    • No instance for (Mu.Schema.Class.GFromSchemaFieldTypeUnion
                         '[ 'DRecord
                              "OneOfTwo"
                              '[ 'FieldDef
                                   "value" ('TUnion '[ 'TPrimitive T.Text, 'TPrimitive Bool])],
                            'DRecord
                              "OneOfThree"
                              '[ 'FieldDef
                                   "value"
                                   ('TUnion
                                      '[ 'TPrimitive T.Text, 'TPrimitive Bool, 'TPrimitive Int32])]]
                         '[ 'TPrimitive Bool, 'TPrimitive Int32]
                         (K1 R (Either Bool Int32)))
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (FromSchema
                                        TheSchema "OneOfThree" OneOfThree)
   |
33 |            , FromSchema TheSchema "OneOfThree")
```

**Comment by serras** [comment]
The easiest way is to create your own `data` with three options:

```haskell
data OneOfThreeValue = A T.Text | B Bool | C Int32
data OneOfThree = OneOfThree { value :: OneOfThreeValue }
```

**Comment by rwakulszowa** [comment]
Oh, it actually does seem to work. I was sure I've tried something along these lines, but I guess I was wrong.

Thanks!

Btw. , if I may make a suggestion - it would be great to see this in the documentation. I can send a PR if you point me to a place where you store the docs.

**Comment by kutyel** [comment]
> Btw. , if I may make a suggestion - it would be great to see this in the documentation. I can send a PR if you point me to a place where you store the docs.

Sure, the docs are here: https://github.com/higherkindness/mu-haskell/tree/master/docs/docs, feel free to contribute a PR! 🙌🏻

**Comment by rwakulszowa** [comment]
Hm, I have another question - does it actually work for more than 3 fields?

```
data OneOfFourValue = A Int32  | B Int32 | C Int32 | D Int32 deriving (Eq, Show, Generic)

data OneOfFour
    = OneOfFour { value :: OneOfFourValue }
     deriving (Eq, Show, Generic, ToSchema TheSchema "OneOfFour", FromSchema TheSchema "OneOfFour")
```

```
message OneOfFour {
  oneof value {
    int32 A = 1;
    int32 B = 2;
    int32 C = 3;
    int32 D = 4;
  }
}
```

Gives a compiler error of
> Overlapping instances for Mu.Schema.Class.GFromSchemaFieldTypeUnion
> ...
> • When deriving the instance for (FromSchema
>                                        TheSchema "OneOfFour" OneOfFour)

Is this expected?

**Comment by serras** [comment]
Let's reopen this to keep track of this problem.

**Comment by llattila** [comment]
I had something that worked with 4 fields but all of the fields were of different type. Might this have an impact on the issue?

Also, is it possible to have only one of the fields with a oneof option while the rest are values that are always required?

```
message OneOfThree {
  int64 unixTime = 1;
  oneof value {
    string a = 2;
    bool b = 3;
    int32 c = 4;
  }
}   
```

**Comment by llattila** [comment]
Yeah, I simply had an issue by using String, not Text, so that caused my issues. The error messages aren't the easiest ones, especially if one has no experience with Template Haskell stuff :)

**Comment by llattila** [comment]
Not sure whether this should be closed as the OneOfFour doesn't seem to work. I tried many different things there locally as well, but was getting those overlapping instance mistakes.

**Comment by llattila** [comment]
I was running some round-trip tests and it seems the oneof always parses only the first type. The encoding created different bytestrings but the decoding only wanted to parse with the first type. Will try to create a simple test-case as my own code-base is already a tad larger as trying to implement it on my previous code base.

**Comment by llattila** [comment]
That location contains the simplest thing I can make fail. Making round trips between OneOfFour and Bytestring and they are clearly not identical. Running the app clearly shows that the proto-buf parsings are different so presume it to fail in the decode only.

https://github.com/llattila/mu-haskell-test-case

**Comment by serras** [comment]
@llattila thanks very much for such a thorough example! 🙇‍♂️ 

I'll have a look at it during next week, I think I have a feeling of where things are going wrong, but I need a bit more digging beforehand.

**Comment by llattila** [comment]
@serras added a validity based test-case as well, should be able to easily identify when things are not working correctly.

**Comment by llattila** [comment]
@serras have you been able to investigate the issue? I tried following up a little bit what happens but can very clearly recognize that I have no clue what is going on with all of this Template Haskell and Type Families :D

**Comment by llattila** [comment]
@serras it seems I might have been only bad at making correct stack files in the test case. Revisited this issue, and noticed my simple-test-case had still extra-dep for the 4.2.0 version in addition to this core/schema version. I Update the project so per the test-case there are no issues in parsing `one ofs`. I think this ticket should be closed.
