### ISSUE TITLE
Bi-Directional streaming gRPC client shows GRpcErrorString

### ISSUE THREAD

**Issue by y-taka-23** [higherkindness/mu-haskell#301]
Trying to connect a bidirectional streaming gRPC server from the following Mu-Haskell client, I got `GRpcErrorString "InvalidState \"stream error\""`. The server is known to work by accessing from BloomRPC.

Currently, I know only request-response (`sayHello`) and server-side streaming (`sayHi`) types of gRPC examples are provided (the following usage is just guessed from signatures). Are the other types of gRPC officially supported?

```haskell
import qualified Data.Conduit.Combinators as CC
import qualified Data.Conduit.List        as CL

main :: IO ()
main = do
    let config = grpcClientConfigSimple "127.0.0.1" 8080 False
    Right client <- setupGrpcClient' config
    let reqs = [ HelloRequest "Alice", HelloRequest "Bob", HelloRequest "Carol" ]
    conduit <- sayManyHellos client
    runConduit $ CL.sourceList reqs .| conduit .| CC.mapM_ print

sayManyHellos :: GrpcClient -> IO (ConduitT HelloRequest (GRpcReply HelloResponse) IO ())
sayManyHellos client =
    gRpcCall @'MsgProtoBuf @Greeter @"Greeter" @"SayManyHellos" client Compressed
```

**Comment by kutyel** [comment]
@serras @akshaymankar is this maybe already fixed with your latest changes? 🤔

**Comment by akshaymankar** [comment]
I initially thought my problem was related to this but I never got the same error as the one reported here and decided that my problem was different. That said, the change is big enough that it could have fixed this issue too. I think easiest might be for @y-taka-23 to retry with grpc-client from HEAD and confirm.

**Comment by serras** [comment]
Closing since it seems that the fix has indeed solved the issue
