### ISSUE TITLE
support capital letter for RPC method names

### ISSUE THREAD

**Issue by listx** [higherkindness/mu-haskell#337]
The protocol buffer style guide at https://developers.google.com/protocol-buffers/docs/style#services says that RPC method names should start with a capital letter. I've noticed that if I use capital letters, at least the "optics" flavored clients don't work because `#MethodName` is invalid whereas `#methodName` is OK. I assume the other styles (records or type applications style) are fine with using capitalized method names but I would like to use the optics style because it feels simpler and appears to be the preferred style of writing clients.

**Comment by serras** [comment]
Unfortunately, starting with lowercase is a limitation of GHC. You can follow the [suggestion from the docs](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/overloaded_labels.html) and use `fromLabel @"MethodName"` in the meanwhile.
