### ISSUE TITLE
How do I convert `GRpcOk a` into a Haskell type?

### ISSUE THREAD

**Issue by listx** [higherkindness/mu-haskell#338]
I could not find a straightforward answer in the docs.

I'm using `Mu.GRpc.Client.Optics` and have a well-formed response (type `GRpcOk a`) where `a` is a mu-haskell Term. I did find https://higherkindness.io/mu-haskell/optics/ but it doesn't actually show you how to get the actual Haskell type.

I've had some luck with using the field accessors like `foo ^. #myfield` but the result is wrapped in a `record` like this: `record MyCoolType ...` when I just want `MyCoolType` directly.

I thought maybe `fromSchema'` might help but I am a bit lost trying to use it without hitting compilation errors.

Am I missing something obvious?

**Comment by serras** [comment]
`GRpcOk` is a constructor, so you can pattern match on it to get the result.

```haskell
case result of
  GRpcOk x -> Just x
  _ -> Nothing
```

**Comment by listx** [comment]
(Forgot to hit "send" before your comment...) Somehow I got this to work... so instead of

```
let foo = fromSchema' @MyCoolType term
```

as suggested in the docs for `fromSchema'`, I did

```
let foo :: MyCoolType = fromSchema' term
```

and it worked. Not sure why the type application didn't work in my case. My code is not open source (yet) so once it is published (hopefully soon?) I might reopen this with a reproducible example.
