### ISSUE TITLE
Deployment support

### ISSUE THREAD

**Issue by serras** [higherkindness/mu-haskell#4]
Investigate what is the easiest approach to deploy using a combination of Stack, Docker, Kubernetes.

**Comment by serras** [comment]
There is now an example of deployment using Docker in the repo.
In theory, deployment using Heroku is also simple, we could add a small tutorial about it.

**Comment by kutyel** [comment]
Consider maybe using this: http://hackage.haskell.org/package/now-haskell

And adding an example of how to deploy one haskell service to [zeit.co](https://zeit.co/) 🤔

**Comment by VladimirLogachev** [comment]
I would like to go through the Heroku deployment and produce a tutorial about it.

**Comment by serras** [comment]
Great! Note that the `deployment` example is *not* up-to-date with respect to the newer versions. If you need so, I can make sure it builds with the last release.

**Comment by serras** [comment]
Closing this out of inactivity.
