### ISSUE TITLE
Please don't use `master` archive of haskell.nix, use a specific reference.

### ISSUE THREAD

**Issue by angerman** [higherkindness/mu-haskell#57]
Great to see this using haskell.nix! Looking thorugh the code, I've seen this line:

https://github.com/higherkindness/mu-haskell/blob/1b6f511acfa93d40f930c2361fec99352c7f1696/default.nix#L1

I'd like to caution against using the `master` archive, and rather put in a git ref instead. Otherwise it's impossible to tell against which version it was built, and any form of issue bisection will be near impossible.

Using https://github.com/input-output-hk/haskell.nix/archive/83966f3.tar.gz would be much better.

**Comment by kutyel** [comment]
Awesome, we’ll do that for sure! Thanks for the heads up! 👏🏼
