### ISSUE TITLE
GraphQL: Add arguments to fields (queries and mutations)

### ISSUE THREAD

**Issue by kutyel** [higherkindness/mu-haskell#79]
**_[requires API design]_**
- [ ] In GraphQL fields may also take arguments, so we need to expand the API.
- [ ] This step also involves some design decisions: currently we lean towards **extending the core schema language**, but other solutions may work too.
- [ ] Code written in (1) and (2) need to be updated to support this new feature.

**Comment by serras** [comment]
No longer makes sense in the new GraphQL roadmap
