### ISSUE TITLE
GraphQL: Convert gRPC <-> GraphQL

### ISSUE THREAD

**Issue by kutyel** [higherkindness/mu-haskell#81]
Figure out how we can directly expose a gRPC server as a GraphQL one with the minimal amount of boilerplate.

*Possible options:*
- **Preferred one:** do some type-level magic to turn the Schema into a bunch of Service’s, along with the corresponding “dumb handler” for each of them. Then turn the original Service into a new Service which refers to the former ones.
- **Another one**: read gRPC schemas following GraphQL semantics, and generate the “dumb handlers” using Template Haskell.

**Comment by serras** [comment]
https://sofa-api.com/ turns GraphQL into REST, maybe we can use it as inspiration.
