### ISSUE TITLE
Make it work with Warp 3.3

### ISSUE THREAD

**Issue by serras** [higherkindness/mu-haskell#85]
Unfortunately, the library we are building upon, `warp-grpc`, has a regression and fails to work with Warp 3.3. Right now the solution is to use Stackage LTS 14.17, because any later snapshots contain the problematic version.

The original ticket is in https://github.com/haskell-grpc-native/http2-grpc-haskell/issues/15. We could push the maintainers, but (un)fortunately I am one of them, so I can put some time to fix it.

**Comment by lucasdicioccio** [comment]
https://hackage.haskell.org/package/warp-grpc-0.3.0.0 much <3 to you for the patch
