### ISSUE TITLE
GraphQL: Write an example client in ReasonML/Elm

### ISSUE THREAD

**Issue by kutyel** [higherkindness/mu-haskell#86]
Once we have the GraphQL servers working, it would be nice to feature a **complete** example using some trendy frontend framework (like ReasonML/Elm) and maybe even blog about it! 😉

**Comment by kutyel** [comment]
Just discovered this https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest and should be very interesting to try it out! 🚀

**Comment by serras** [comment]
For the Reason client, we should use the [official Apollo libraries](https://github.com/apollographql/reason-apollo) to ensure conformance with the main implementation,

**Comment by kutyel** [comment]
This task is finished!
- Elm example: https://github.com/higherkindness/mu-graphql-example-elm
- Reason example: https://github.com/higherkindness/mu-graphql-example-reason

**Comment by serras** [comment]
Could you add a link to these repos in the `graphql` folder?

**Comment by kutyel** [comment]
Sure! 😄
